config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'notes#index'
  resources :notes, only: [:index, :update, :destroy, :create, :new, :edit, :show] 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト" 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller? 
    before_action :authenticate_user!

    private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,keys:[:email, :name]) 
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user! 


  def index
    @note_new = Note.new
    @user = current_user
    @notes = @user.notes 
    
  end

  def create
    @note_new = Note.new(notes_params)
    @note_new.user = current_user
    @note = Note.new(notes_params)
    
    respond_to do |format|
      if @note_new.save     
        format.turbo_stream
      else
        flash[:turbo_create_alert] = "Descriptionは空にはできません。"
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end


  def edit
    @note = Note.find(params[:id])
  end


  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update(notes_params)
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        flash[:turbo_update_alert] = "Descriptionは空にはできません。"
      end
    end
  end

  def destroy
    @note = Note.find(params[:id])
    
    respond_to do |format|
      if @note.destroy
        format.turbo_stream
      end
    end
     
  end

  def show
    @note = Note.find(params[:id])
  end
  

  def new
    @note = Note.new
  end

  private
  
  def notes_params
    params.require(:note).permit(:user_id, :title, :description, :status_progress)
  end



end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
 

    <!-- リセットCSS -->
    <link rel="stylesheet" href ="https://cdn.skypack.dev/sanitize.css">
    <!-- スタイルシート　-->
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
      
    <meta name="turbo-cache-control" content="no-cache">

    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
  </head>

  <body>
  
    <header>
      <h1>study note app</h1>
      <% if flash[:turbo_alert].present? %>
        <div class="alert alert-warning mr-2">
          <%= flash[:turbo_alert] %>
        </div>
      <% end %>
      <div class="d-flex justify-content-end align-items-center">
        <% if notice.present? %>
          <div class="alert alert-primary mr-2">
            <%= notice %>
          </div>
        <% end %>

        <% if alert.present? %>
          <div class="alert alert-warning mr-2">
            <%= alert %>
          </div>
        <% end %>

        <ul class="nav justify-content-end">
        <div class="row">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to edit_user_registration_path, class: "nav-link" do%>
                <i class="ri-user-line">Account</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do%>
               <i class="ri-logout-box-line">Log out</i>
              <% end %>
            </li>
            <li class="nav-item">
              <h5><%= current_user.name %>:ログイン中</h5>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link" do%>
               <i class="ri-user-add-line">Sign up</i>
              <% end %> 
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link" do%>
               <i class="ri-login-box-line">Log in</i>
              <% end %>
            </li>
          <% end %>
          </div>   
        </ul>
      </div>                
        
        
    </header>

    <%= turbo_frame_tag 'modal' %>

    <%= yield %>
    <script>
    $(function(){
      $(".alert, .notice").fadeOut(5000);
    });
    </script>


    <footer>
      <p>© <%= Time.now.year %> study note app.</p>
      <p>Created by: fujimaki</p>
    </footer>
    
  </body>
</html>

app/views/notes/_destroy_form.html.erb
<%= turbo_frame_tag "modal" do %>
    <%= form_with(model: note, method: :delete, html: { data: { action: 'turbo:submit-end->modal#close' } }) do |form| %>
        <%= note.description %><br>
        <h5>noteを削除してよろしいですか？</h5>
        <%= button_to 'Delete', note, data: { turbo_method: :delete } ,class:"delete_color"%>
    <% end %>
<% end %>

app/views/notes/_edit_form.html.erb
<%= turbo_frame_tag id="new" do %>

    <%= form_with(model: note, html: { data: {action: 'turbo:submit-end->modal#close'}}) do |form| %>

        <% if flash[:turbo_update_alert].present? %>
            <div class="alert alert-warning mr-2">
              <%= flash[:turbo_update_alert] %>
            </div>
        <% end %>
        <%= form.label :title, style: "display: block" %>
        <%= form.text_field :title %>
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description %>
        <%= form.submit "Update" %>
    <% end %>
<% end %>

app/views/notes/_new_form.html.erb
<%= turbo_frame_tag id="new" do %>

  <%= form_with(model: note, html: { data: {action: 'turbo:submit-end->modal#close'}}) do |form| %>
  
 
        <% if flash[:turbo_create_alert].present? %>
          <div class="alert alert-warning mr-2">
            <%= flash[:turbo_create_alert] %>
          </div>
        <% end %>
  
        <div>
          <%= form.label :title, style: "display: block" %>
          <%= form.text_field :title %>
        </div>
        <div>
          <%= form.label :description, style: "display: block" %>
          <%= form.text_area :description %>
        </div>
    
  
      <div>
        <%= form.submit "Create New" %>
      </div>
  <% end %>
  
  
  <% end %>
 

app/views/notes/_note.html.erb
<div id="note_<%= note.id %>" style="padding: 5px; margin: 10px 0">
  <div class="card">
    <% frame_id = dom_id(note, "modal") %>
      <%= form_with model: note, data: { turbo_frame: frame_id } do %>
        <%= turbo_frame_tag frame_id do %>
          <div class="card-header">
            <ul class="nav justify-content-end">
              <div class="col">Note</div>
              <%= link_to  note_path(note), class: "btn btn-default", data: { turbo_stream: true ,turbo_frame: 'modal'} do %>
                <i class="ri-delete-bin-6-line">Delete</i>
              <% end %>
              <%= link_to  edit_note_path(note), class: "btn btn-default", data: { turbo_stream: true ,turbo_frame: 'modal'} do %>
                <i class="ri-edit-box-line">Edit</i>
              <% end %>
            </ul>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= note.title %></h5>            
              <br>
              <p class="card-text"><%=safe_join(note.description.split("\n"),tag(:br))%></p>
          </div>
          <%= render partial: 'status_progress_buttons', locals: { note: note } %>
        <% end %>
      <% end %>
      </div>
  </div>
</div>

app/views/notes/_status_progress_buttons.html.erb
<% statuses = { 0 => "planned", 1 => "progress", 2 => "done" } %>
<% statuses_btn_enabled = { 0 => "bulb_color_0", 1 => "bulb_color_1", 2 => "bulb_color_2" } %>
<% statuses_btn_disabled = { 0 => "bulb_color_0", 1 => "bulb_color_1", 2 => "bulb_color_2" } %>

<ul class="nav justify-content-end">
  <% statuses.each do |status, value| %>        
    <%= form_with model: note, url: note_path(note.id), local: true, method: :patch do |form| %>
      <%= form.hidden_field :status_progress, value: status , readonly: true %>
        <% if status == note.status_progress %>
          <%= button_tag type: "submit", class: "btn btn-default" do %>
            <div class= <%= statuses_btn_enabled[status] %> >
              <i class="ri-lightbulb-flash-fill"></i>
            <div/>
          <% end %>
        <% else  %>
          <%= button_tag type: "submit", class: "btn btn-default" do %>
            <div class= <%= statuses_btn_disabled[status] %> >
              <i class="ri-lightbulb-line"></i>
            <div/>
          <% end %>
        <% end %>
    <% end %>
  <% end %>
</ul>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.prepend "notes", @note_new %>

app/views/notes/destroy.turbo_stream.erb
<%= turbo_stream.remove @note %>

app/views/notes/edit.html.erb
<%= turbo_frame_tag id="modal" do %>
     <div class="modal fade" tabindex="-1"
         data-controller="modal">
     <div class="modal-dialog modal-lg">
       <div class="modal-content">
         <div class="modal-header">
           <h5 class="modal-title">編集</h5>
           <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
         </div>
         <div class="modal-body">
           <%= render "edit_form", note: @note%>
         </div>
       </div>
     </div>
   </div>
<% end %>
   

app/views/notes/index.html.erb
<ul class="nav">
  <%= link_to  new_note_path, class: "btn btn-default" , data: { turbo_frame: 'modal'} do %>
    <i class="ri-sticky-note-line">new note</i>
  <% end %>
</ul>

<div id="notes">
  <% if @notes.present? %>
      <% @notes.reverse.each do |note| %>
        <%= render note %>
      <% end %>
  <% end %>
</div>

app/views/notes/new.html.erb
<%= turbo_frame_tag 'modal' do %>
    <div class="modal fade" tabindex="-1"
        data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">新規作成</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <%= render "new_form", note: @note %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/notes/show.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal fade" tabindex="-1"
      data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= @note.title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">       
        <%= render "destroy_form", note: @note%>

        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/notes/update.turbo_stream.erb
<%= turbo_stream.replace @note %>